/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTekRouteImport } from './routes/_app.tek'
import { Route as AppStrategiesRouteImport } from './routes/_app.strategies'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppTekTeamRouteImport } from './routes/_app.tek.team'
import { Route as AppTekProjectsRouteImport } from './routes/_app.tek.projects'
import { Route as AppTekLeadsRouteImport } from './routes/_app.tek.leads'
import { Route as AppTekInvoicesRouteImport } from './routes/_app.tek.invoices'
import { Route as AppTekExpensesRouteImport } from './routes/_app.tek.expenses'
import { Route as AppTekClientsRouteImport } from './routes/_app.tek.clients'
import { Route as AppStrategiesTeamRouteImport } from './routes/_app.strategies.team'
import { Route as AppStrategiesProjectsRouteImport } from './routes/_app.strategies.projects'
import { Route as AppStrategiesLeadsRouteImport } from './routes/_app.strategies.leads'
import { Route as AppStrategiesInvoicesRouteImport } from './routes/_app.strategies.invoices'
import { Route as AppStrategiesClientsRouteImport } from './routes/_app.strategies.clients'
import { Route as AppStrategiesAssetsRouteImport } from './routes/_app.strategies.assets'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTekRoute = AppTekRouteImport.update({
  id: '/tek',
  path: '/tek',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategiesRoute = AppStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTekTeamRoute = AppTekTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppTekRoute,
} as any)
const AppTekProjectsRoute = AppTekProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppTekRoute,
} as any)
const AppTekLeadsRoute = AppTekLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppTekRoute,
} as any)
const AppTekInvoicesRoute = AppTekInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppTekRoute,
} as any)
const AppTekExpensesRoute = AppTekExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppTekRoute,
} as any)
const AppTekClientsRoute = AppTekClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppTekRoute,
} as any)
const AppStrategiesTeamRoute = AppStrategiesTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppStrategiesRoute,
} as any)
const AppStrategiesProjectsRoute = AppStrategiesProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppStrategiesRoute,
} as any)
const AppStrategiesLeadsRoute = AppStrategiesLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppStrategiesRoute,
} as any)
const AppStrategiesInvoicesRoute = AppStrategiesInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppStrategiesRoute,
} as any)
const AppStrategiesClientsRoute = AppStrategiesClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppStrategiesRoute,
} as any)
const AppStrategiesAssetsRoute = AppStrategiesAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppStrategiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/strategies': typeof AppStrategiesRouteWithChildren
  '/tek': typeof AppTekRouteWithChildren
  '/strategies/assets': typeof AppStrategiesAssetsRoute
  '/strategies/clients': typeof AppStrategiesClientsRoute
  '/strategies/invoices': typeof AppStrategiesInvoicesRoute
  '/strategies/leads': typeof AppStrategiesLeadsRoute
  '/strategies/projects': typeof AppStrategiesProjectsRoute
  '/strategies/team': typeof AppStrategiesTeamRoute
  '/tek/clients': typeof AppTekClientsRoute
  '/tek/expenses': typeof AppTekExpensesRoute
  '/tek/invoices': typeof AppTekInvoicesRoute
  '/tek/leads': typeof AppTekLeadsRoute
  '/tek/projects': typeof AppTekProjectsRoute
  '/tek/team': typeof AppTekTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/strategies': typeof AppStrategiesRouteWithChildren
  '/tek': typeof AppTekRouteWithChildren
  '/strategies/assets': typeof AppStrategiesAssetsRoute
  '/strategies/clients': typeof AppStrategiesClientsRoute
  '/strategies/invoices': typeof AppStrategiesInvoicesRoute
  '/strategies/leads': typeof AppStrategiesLeadsRoute
  '/strategies/projects': typeof AppStrategiesProjectsRoute
  '/strategies/team': typeof AppStrategiesTeamRoute
  '/tek/clients': typeof AppTekClientsRoute
  '/tek/expenses': typeof AppTekExpensesRoute
  '/tek/invoices': typeof AppTekInvoicesRoute
  '/tek/leads': typeof AppTekLeadsRoute
  '/tek/projects': typeof AppTekProjectsRoute
  '/tek/team': typeof AppTekTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/strategies': typeof AppStrategiesRouteWithChildren
  '/_app/tek': typeof AppTekRouteWithChildren
  '/_app/strategies/assets': typeof AppStrategiesAssetsRoute
  '/_app/strategies/clients': typeof AppStrategiesClientsRoute
  '/_app/strategies/invoices': typeof AppStrategiesInvoicesRoute
  '/_app/strategies/leads': typeof AppStrategiesLeadsRoute
  '/_app/strategies/projects': typeof AppStrategiesProjectsRoute
  '/_app/strategies/team': typeof AppStrategiesTeamRoute
  '/_app/tek/clients': typeof AppTekClientsRoute
  '/_app/tek/expenses': typeof AppTekExpensesRoute
  '/_app/tek/invoices': typeof AppTekInvoicesRoute
  '/_app/tek/leads': typeof AppTekLeadsRoute
  '/_app/tek/projects': typeof AppTekProjectsRoute
  '/_app/tek/team': typeof AppTekTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/settings'
    | '/strategies'
    | '/tek'
    | '/strategies/assets'
    | '/strategies/clients'
    | '/strategies/invoices'
    | '/strategies/leads'
    | '/strategies/projects'
    | '/strategies/team'
    | '/tek/clients'
    | '/tek/expenses'
    | '/tek/invoices'
    | '/tek/leads'
    | '/tek/projects'
    | '/tek/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/settings'
    | '/strategies'
    | '/tek'
    | '/strategies/assets'
    | '/strategies/clients'
    | '/strategies/invoices'
    | '/strategies/leads'
    | '/strategies/projects'
    | '/strategies/team'
    | '/tek/clients'
    | '/tek/expenses'
    | '/tek/invoices'
    | '/tek/leads'
    | '/tek/projects'
    | '/tek/team'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/strategies'
    | '/_app/tek'
    | '/_app/strategies/assets'
    | '/_app/strategies/clients'
    | '/_app/strategies/invoices'
    | '/_app/strategies/leads'
    | '/_app/strategies/projects'
    | '/_app/strategies/team'
    | '/_app/tek/clients'
    | '/_app/tek/expenses'
    | '/_app/tek/invoices'
    | '/_app/tek/leads'
    | '/_app/tek/projects'
    | '/_app/tek/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tek': {
      id: '/_app/tek'
      path: '/tek'
      fullPath: '/tek'
      preLoaderRoute: typeof AppTekRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/strategies': {
      id: '/_app/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AppStrategiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tek/team': {
      id: '/_app/tek/team'
      path: '/team'
      fullPath: '/tek/team'
      preLoaderRoute: typeof AppTekTeamRouteImport
      parentRoute: typeof AppTekRoute
    }
    '/_app/tek/projects': {
      id: '/_app/tek/projects'
      path: '/projects'
      fullPath: '/tek/projects'
      preLoaderRoute: typeof AppTekProjectsRouteImport
      parentRoute: typeof AppTekRoute
    }
    '/_app/tek/leads': {
      id: '/_app/tek/leads'
      path: '/leads'
      fullPath: '/tek/leads'
      preLoaderRoute: typeof AppTekLeadsRouteImport
      parentRoute: typeof AppTekRoute
    }
    '/_app/tek/invoices': {
      id: '/_app/tek/invoices'
      path: '/invoices'
      fullPath: '/tek/invoices'
      preLoaderRoute: typeof AppTekInvoicesRouteImport
      parentRoute: typeof AppTekRoute
    }
    '/_app/tek/expenses': {
      id: '/_app/tek/expenses'
      path: '/expenses'
      fullPath: '/tek/expenses'
      preLoaderRoute: typeof AppTekExpensesRouteImport
      parentRoute: typeof AppTekRoute
    }
    '/_app/tek/clients': {
      id: '/_app/tek/clients'
      path: '/clients'
      fullPath: '/tek/clients'
      preLoaderRoute: typeof AppTekClientsRouteImport
      parentRoute: typeof AppTekRoute
    }
    '/_app/strategies/team': {
      id: '/_app/strategies/team'
      path: '/team'
      fullPath: '/strategies/team'
      preLoaderRoute: typeof AppStrategiesTeamRouteImport
      parentRoute: typeof AppStrategiesRoute
    }
    '/_app/strategies/projects': {
      id: '/_app/strategies/projects'
      path: '/projects'
      fullPath: '/strategies/projects'
      preLoaderRoute: typeof AppStrategiesProjectsRouteImport
      parentRoute: typeof AppStrategiesRoute
    }
    '/_app/strategies/leads': {
      id: '/_app/strategies/leads'
      path: '/leads'
      fullPath: '/strategies/leads'
      preLoaderRoute: typeof AppStrategiesLeadsRouteImport
      parentRoute: typeof AppStrategiesRoute
    }
    '/_app/strategies/invoices': {
      id: '/_app/strategies/invoices'
      path: '/invoices'
      fullPath: '/strategies/invoices'
      preLoaderRoute: typeof AppStrategiesInvoicesRouteImport
      parentRoute: typeof AppStrategiesRoute
    }
    '/_app/strategies/clients': {
      id: '/_app/strategies/clients'
      path: '/clients'
      fullPath: '/strategies/clients'
      preLoaderRoute: typeof AppStrategiesClientsRouteImport
      parentRoute: typeof AppStrategiesRoute
    }
    '/_app/strategies/assets': {
      id: '/_app/strategies/assets'
      path: '/assets'
      fullPath: '/strategies/assets'
      preLoaderRoute: typeof AppStrategiesAssetsRouteImport
      parentRoute: typeof AppStrategiesRoute
    }
  }
}

interface AppStrategiesRouteChildren {
  AppStrategiesAssetsRoute: typeof AppStrategiesAssetsRoute
  AppStrategiesClientsRoute: typeof AppStrategiesClientsRoute
  AppStrategiesInvoicesRoute: typeof AppStrategiesInvoicesRoute
  AppStrategiesLeadsRoute: typeof AppStrategiesLeadsRoute
  AppStrategiesProjectsRoute: typeof AppStrategiesProjectsRoute
  AppStrategiesTeamRoute: typeof AppStrategiesTeamRoute
}

const AppStrategiesRouteChildren: AppStrategiesRouteChildren = {
  AppStrategiesAssetsRoute: AppStrategiesAssetsRoute,
  AppStrategiesClientsRoute: AppStrategiesClientsRoute,
  AppStrategiesInvoicesRoute: AppStrategiesInvoicesRoute,
  AppStrategiesLeadsRoute: AppStrategiesLeadsRoute,
  AppStrategiesProjectsRoute: AppStrategiesProjectsRoute,
  AppStrategiesTeamRoute: AppStrategiesTeamRoute,
}

const AppStrategiesRouteWithChildren = AppStrategiesRoute._addFileChildren(
  AppStrategiesRouteChildren,
)

interface AppTekRouteChildren {
  AppTekClientsRoute: typeof AppTekClientsRoute
  AppTekExpensesRoute: typeof AppTekExpensesRoute
  AppTekInvoicesRoute: typeof AppTekInvoicesRoute
  AppTekLeadsRoute: typeof AppTekLeadsRoute
  AppTekProjectsRoute: typeof AppTekProjectsRoute
  AppTekTeamRoute: typeof AppTekTeamRoute
}

const AppTekRouteChildren: AppTekRouteChildren = {
  AppTekClientsRoute: AppTekClientsRoute,
  AppTekExpensesRoute: AppTekExpensesRoute,
  AppTekInvoicesRoute: AppTekInvoicesRoute,
  AppTekLeadsRoute: AppTekLeadsRoute,
  AppTekProjectsRoute: AppTekProjectsRoute,
  AppTekTeamRoute: AppTekTeamRoute,
}

const AppTekRouteWithChildren =
  AppTekRoute._addFileChildren(AppTekRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStrategiesRoute: typeof AppStrategiesRouteWithChildren
  AppTekRoute: typeof AppTekRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStrategiesRoute: AppStrategiesRouteWithChildren,
  AppTekRoute: AppTekRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
